export enum Screens {
  APP = 'APP',

  // Bottom Tab
  HOME = 'HOME',
  FAVORITE = 'FAVORITE',
  ADD = 'ADD',
  KNOWLEDGE = 'KNOWLEDGE',
  PROFILE = 'PROFILE',

  // Main
  ADD_APPLICATION = 'ADD_APPLICATION',
  IN_APPLICATION = 'IN_APPLICATION',
  ADDRESS = 'ADDRESS',

  //Auth
  AUTH = 'AUTH',
  REGISTRATION = 'REGISTRATION',
}
