export enum Screens {
  APP = 'APP',

  HOME = 'HOME',
  FAVORITE = 'FAVORITE',
  ADD = 'ADD',
  KNOWLEDGE = 'KNOWLEDGE',
  PROFILE = 'PROFILE',

  ADD_APPLICATION = 'ADD_APPLICATION',
  IN_APPLICATION = 'IN_APPLICATION',
}
